"""Ajout photo_url

Revision ID: 0d5a5cf29d20
Revises: a6fb850218bc
Create Date: 2026-04-25 19:24:43.868998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d5a5cf29d20'
down_revision = 'a6fb850218bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coiffeurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('galerie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=500), nullable=False))

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('temoignages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('video_url')
        batch_op.drop_column('logo_url')

    with op.batch_alter_table('temoignages', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    with op.batch_alter_table('galerie', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    with op.batch_alter_table('coiffeurs', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
