"""Ajout couverture

Revision ID: 0d537fb75d00
Revises: 0d5a5cf29d20
Create Date: 2026-04-27 08:51:52.914057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d537fb75d00'
down_revision = '0d5a5cf29d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_cloudinary_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cover_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('cover_url')
        batch_op.drop_column('cover_cloudinary_id')

    # ### end Alembic commands ###
