"""Ajout colonnes services manquantes

Revision ID: 0eefdb414d73
Revises: 0d537fb75d00
Create Date: 2026-05-01 15:39:43.914442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0eefdb414d73'
down_revision = '0d537fb75d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('service_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'services', ['service_id'], ['id'])

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.create_index(batch_op.f('ix_reservations_tenant_slug'), ['tenant_slug'], unique=False)
        batch_op.drop_constraint(batch_op.f('reservations_tenant_slug_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_slug'], ['slug'])
        batch_op.create_foreign_key(None, 'services', ['service_id'], ['id'])

    with op.batch_alter_table('salon_categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('salon_categories_tenant_slug_categorie_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_salon_categories_tenant_slug'), ['tenant_slug'], unique=False)
        batch_op.create_unique_constraint('unique_salon_category', ['tenant_slug', 'categorie'])
        batch_op.drop_constraint(batch_op.f('salon_categories_tenant_slug_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_slug'], ['slug'])

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_tenant_slug'), ['tenant_slug'], unique=False)
        batch_op.drop_constraint(batch_op.f('services_tenant_slug_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_slug'], ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('services_tenant_slug_fkey'), 'tenants', ['tenant_slug'], ['slug'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_services_tenant_slug'))

    with op.batch_alter_table('salon_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('salon_categories_tenant_slug_fkey'), 'tenants', ['tenant_slug'], ['slug'], ondelete='CASCADE')
        batch_op.drop_constraint('unique_salon_category', type_='unique')
        batch_op.drop_index(batch_op.f('ix_salon_categories_tenant_slug'))
        batch_op.create_unique_constraint(batch_op.f('salon_categories_tenant_slug_categorie_key'), ['tenant_slug', 'categorie'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reservations_tenant_slug_fkey'), 'tenants', ['tenant_slug'], ['slug'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_reservations_tenant_slug'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('service_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
