"""Initial migration

Revision ID: a6fb850218bc
Revises: 
Create Date: 2026-04-25 13:45:49.896041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6fb850218bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('adresse_text', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('logo_cloudinary_id', sa.String(length=200), nullable=True),
    sa.Column('video_hero_cloudinary_id', sa.String(length=200), nullable=True),
    sa.Column('theme_json', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_payment_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_slug'), ['slug'], unique=True)

    op.create_table('coiffeurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_slug', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('photo_cloudinary_id', sa.String(length=200), nullable=True),
    sa.Column('specialite', sa.String(length=200), nullable=True),
    sa.Column('instagram', sa.String(length=100), nullable=True),
    sa.Column('annees_exp', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_slug'], ['tenants.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coiffeurs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coiffeurs_tenant_slug'), ['tenant_slug'], unique=False)

    op.create_table('galerie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_slug', sa.String(length=50), nullable=False),
    sa.Column('photo_cloudinary_id', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('legende', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['tenant_slug'], ['tenants.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('galerie', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_galerie_tenant_slug'), ['tenant_slug'], unique=False)

    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_slug', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_slug'], ['tenants.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_tenant_slug'), ['tenant_slug'], unique=False)

    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_slug', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('prix_barre', sa.Float(), nullable=True),
    sa.Column('duree_min', sa.Integer(), nullable=True),
    sa.Column('photo_cloudinary_id', sa.String(length=200), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('description_psycho', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_slug'], ['tenants.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_tenant_slug'), ['tenant_slug'], unique=False)

    op.create_table('temoignages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_slug', sa.String(length=50), nullable=False),
    sa.Column('client_nom', sa.String(length=100), nullable=True),
    sa.Column('texte', sa.Text(), nullable=True),
    sa.Column('note', sa.Integer(), nullable=True),
    sa.Column('photo_cloudinary_id', sa.String(length=200), nullable=True),
    sa.Column('consentement_photo', sa.Boolean(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_slug'], ['tenants.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('temoignages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_temoignages_tenant_slug'), ['tenant_slug'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('tenant_slug', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_slug'], ['tenants.slug'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_tenant_slug'), ['tenant_slug'], unique=False)

    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_slug', sa.String(length=50), nullable=False),
    sa.Column('client_nom', sa.String(length=100), nullable=False),
    sa.Column('client_phone', sa.String(length=20), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('coiffeur_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('acompte_tx_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['coiffeur_id'], ['coiffeurs.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['tenant_slug'], ['tenants.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_tenant_slug'), ['tenant_slug'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_tenant_slug'))

    op.drop_table('bookings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_slug'))

    op.drop_table('users')
    with op.batch_alter_table('temoignages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temoignages_tenant_slug'))

    op.drop_table('temoignages')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_tenant_slug'))

    op.drop_table('services')
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_tenant_slug'))

    op.drop_table('logs')
    with op.batch_alter_table('galerie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_galerie_tenant_slug'))

    op.drop_table('galerie')
    with op.batch_alter_table('coiffeurs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coiffeurs_tenant_slug'))

    op.drop_table('coiffeurs')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_slug'))

    op.drop_table('tenants')
    # ### end Alembic commands ###
